// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {studioapp} from '../models';
import {httpapi} from '../models';

export function AssistQuery(arg1:studioapp.assistantQueryRequest):Promise<studioapp.assistantQueryResponse>;

export function AssistantLLMCatalog():Promise<studioapp.assistantLLMCatalog>;

export function Begin(arg1:studioapp.beginRequest):Promise<Record<string, any>>;

export function ClusterDiagnostics():Promise<Record<string, any>>;

export function ClusterGroups():Promise<Record<string, any>>;

export function ClusterNodeStatus():Promise<Record<string, any>>;

export function ClusterStatus(arg1:string):Promise<Record<string, any>>;

export function Commit(arg1:studioapp.txRequest):Promise<Record<string, any>>;

export function ConnectionInfo():Promise<Record<string, any>>;

export function Domains():Promise<Record<string, any>>;

export function EngineStats():Promise<Record<string, any>>;

export function EntityVersionHistory(arg1:studioapp.entityVersionHistoryRequest):Promise<Record<string, any>>;

export function Execute(arg1:studioapp.executeRequest):Promise<Record<string, any>>;

export function ExecuteBatch(arg1:studioapp.executeBatchRequest):Promise<Record<string, any>>;

export function Explain(arg1:studioapp.explainRequest):Promise<Record<string, any>>;

export function FixtureExport(arg1:studioapp.fixtureExportRequest):Promise<Record<string, any>>;

export function FixtureLoad(arg1:string):Promise<Record<string, any>>;

export function FixtureValidate(arg1:string):Promise<Record<string, any>>;

export function Health():Promise<Record<string, any>>;

export function PickFixtureExportFile(arg1:string):Promise<string>;

export function PickFixtureFile():Promise<string>;

export function ReadQuery(arg1:studioapp.readQueryRequest):Promise<studioapp.readQueryResponse>;

export function ReadRoutingStats():Promise<Record<string, any>>;

export function RecoveryBackupManifest(arg1:string):Promise<Record<string, any>>;

export function RecoveryCreateBackup(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RecoveryDefaults():Promise<Record<string, any>>;

export function RecoveryRestoreLSN(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function RecoveryRestoreTimestamp(arg1:string,arg2:string,arg3:number):Promise<Record<string, any>>;

export function RecoverySnapshotCatalog(arg1:string):Promise<Record<string, any>>;

export function RecoveryVerifyBackup(arg1:string):Promise<Record<string, any>>;

export function RecoveryWALRetention(arg1:string):Promise<Record<string, any>>;

export function ReplicationLag():Promise<Record<string, any>>;

export function ReplicationLastLSN():Promise<Record<string, any>>;

export function Rollback(arg1:studioapp.txRequest):Promise<Record<string, any>>;

export function RowHistory(arg1:studioapp.rowHistoryRequest):Promise<Record<string, any>>;

export function SaveBinaryFile(arg1:string,arg2:string):Promise<void>;

export function SaveTextFile(arg1:string,arg2:string):Promise<void>;

export function ScanStrategyStats():Promise<Record<string, any>>;

export function SchemaApply(arg1:studioapp.schemaDDLRequest):Promise<Record<string, any>>;

export function SchemaApplySafeDiff(arg1:studioapp.schemaDiffRequest):Promise<Record<string, any>>;

export function SchemaApplyStatements(arg1:studioapp.schemaApplyStatementsRequest):Promise<Record<string, any>>;

export function SchemaDDL(arg1:studioapp.schemaDDLRequest):Promise<Record<string, any>>;

export function SchemaDiff(arg1:studioapp.schemaDiffRequest):Promise<Record<string, any>>;

export function SchemaLoadAllBaselines():Promise<Record<string, any>>;

export function SchemaLoadBaseline(arg1:studioapp.schemaLoadBaselineRequest):Promise<Record<string, any>>;

export function SchemaTables(arg1:string):Promise<Record<string, any>>;

export function SecurityBootstrapAdmin(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SecurityCreateRole(arg1:string):Promise<Record<string, any>>;

export function SecurityCreateUser(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SecurityDeletePrincipal(arg1:string):Promise<Record<string, any>>;

export function SecurityDisablePrincipal(arg1:string):Promise<Record<string, any>>;

export function SecurityEnablePrincipal(arg1:string):Promise<Record<string, any>>;

export function SecurityGrantHistoricalAccess(arg1:string):Promise<Record<string, any>>;

export function SecurityGrantPrivilege(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SecurityGrantRole(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SecurityListPrincipals():Promise<Record<string, any>>;

export function SecurityRecentAuditEvents(arg1:number):Promise<Record<string, any>>;

export function SecurityRevokePrivilege(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SecurityRevokeRole(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SecuritySetPassword(arg1:string,arg2:string):Promise<Record<string, any>>;

export function StartEntityChangeStream(arg1:studioapp.entityChangeStreamStartRequest):Promise<Record<string, any>>;

export function StopEntityChangeStream(arg1:studioapp.entityChangeStreamStopRequest):Promise<Record<string, any>>;

export function SwitchConnection(arg1:studioapp.connectionSwitchRequest):Promise<Record<string, any>>;

export function TemporalLookup(arg1:studioapp.temporalLookupRequest):Promise<Record<string, any>>;

export function TimeTravel(arg1:studioapp.timeTravelRequest):Promise<Record<string, any>>;

export function TimelineCommits(arg1:httpapi.TimelineCommitsRequest):Promise<Record<string, any>>;
