// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssistQuery(arg1) {
  return window['go']['studioapp']['App']['AssistQuery'](arg1);
}

export function AssistantLLMCatalog() {
  return window['go']['studioapp']['App']['AssistantLLMCatalog']();
}

export function Begin(arg1) {
  return window['go']['studioapp']['App']['Begin'](arg1);
}

export function ClusterDiagnostics() {
  return window['go']['studioapp']['App']['ClusterDiagnostics']();
}

export function ClusterGroups() {
  return window['go']['studioapp']['App']['ClusterGroups']();
}

export function ClusterNodeStatus() {
  return window['go']['studioapp']['App']['ClusterNodeStatus']();
}

export function ClusterStatus(arg1) {
  return window['go']['studioapp']['App']['ClusterStatus'](arg1);
}

export function Commit(arg1) {
  return window['go']['studioapp']['App']['Commit'](arg1);
}

export function ConnectionInfo() {
  return window['go']['studioapp']['App']['ConnectionInfo']();
}

export function Domains() {
  return window['go']['studioapp']['App']['Domains']();
}

export function EngineStats() {
  return window['go']['studioapp']['App']['EngineStats']();
}

export function EntityVersionHistory(arg1) {
  return window['go']['studioapp']['App']['EntityVersionHistory'](arg1);
}

export function Execute(arg1) {
  return window['go']['studioapp']['App']['Execute'](arg1);
}

export function ExecuteBatch(arg1) {
  return window['go']['studioapp']['App']['ExecuteBatch'](arg1);
}

export function Explain(arg1) {
  return window['go']['studioapp']['App']['Explain'](arg1);
}

export function FixtureExport(arg1) {
  return window['go']['studioapp']['App']['FixtureExport'](arg1);
}

export function FixtureLoad(arg1) {
  return window['go']['studioapp']['App']['FixtureLoad'](arg1);
}

export function FixtureValidate(arg1) {
  return window['go']['studioapp']['App']['FixtureValidate'](arg1);
}

export function Health() {
  return window['go']['studioapp']['App']['Health']();
}

export function PickFixtureExportFile(arg1) {
  return window['go']['studioapp']['App']['PickFixtureExportFile'](arg1);
}

export function PickFixtureFile() {
  return window['go']['studioapp']['App']['PickFixtureFile']();
}

export function ReadQuery(arg1) {
  return window['go']['studioapp']['App']['ReadQuery'](arg1);
}

export function ReadRoutingStats() {
  return window['go']['studioapp']['App']['ReadRoutingStats']();
}

export function RecoveryBackupManifest(arg1) {
  return window['go']['studioapp']['App']['RecoveryBackupManifest'](arg1);
}

export function RecoveryCreateBackup(arg1, arg2) {
  return window['go']['studioapp']['App']['RecoveryCreateBackup'](arg1, arg2);
}

export function RecoveryDefaults() {
  return window['go']['studioapp']['App']['RecoveryDefaults']();
}

export function RecoveryRestoreLSN(arg1, arg2, arg3) {
  return window['go']['studioapp']['App']['RecoveryRestoreLSN'](arg1, arg2, arg3);
}

export function RecoveryRestoreTimestamp(arg1, arg2, arg3) {
  return window['go']['studioapp']['App']['RecoveryRestoreTimestamp'](arg1, arg2, arg3);
}

export function RecoverySnapshotCatalog(arg1) {
  return window['go']['studioapp']['App']['RecoverySnapshotCatalog'](arg1);
}

export function RecoveryVerifyBackup(arg1) {
  return window['go']['studioapp']['App']['RecoveryVerifyBackup'](arg1);
}

export function RecoveryWALRetention(arg1) {
  return window['go']['studioapp']['App']['RecoveryWALRetention'](arg1);
}

export function ReplicationLag() {
  return window['go']['studioapp']['App']['ReplicationLag']();
}

export function ReplicationLastLSN() {
  return window['go']['studioapp']['App']['ReplicationLastLSN']();
}

export function Rollback(arg1) {
  return window['go']['studioapp']['App']['Rollback'](arg1);
}

export function RowHistory(arg1) {
  return window['go']['studioapp']['App']['RowHistory'](arg1);
}

export function SaveBinaryFile(arg1, arg2) {
  return window['go']['studioapp']['App']['SaveBinaryFile'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2) {
  return window['go']['studioapp']['App']['SaveTextFile'](arg1, arg2);
}

export function ScanStrategyStats() {
  return window['go']['studioapp']['App']['ScanStrategyStats']();
}

export function SchemaApply(arg1) {
  return window['go']['studioapp']['App']['SchemaApply'](arg1);
}

export function SchemaApplySafeDiff(arg1) {
  return window['go']['studioapp']['App']['SchemaApplySafeDiff'](arg1);
}

export function SchemaApplyStatements(arg1) {
  return window['go']['studioapp']['App']['SchemaApplyStatements'](arg1);
}

export function SchemaDDL(arg1) {
  return window['go']['studioapp']['App']['SchemaDDL'](arg1);
}

export function SchemaDiff(arg1) {
  return window['go']['studioapp']['App']['SchemaDiff'](arg1);
}

export function SchemaLoadAllBaselines() {
  return window['go']['studioapp']['App']['SchemaLoadAllBaselines']();
}

export function SchemaLoadBaseline(arg1) {
  return window['go']['studioapp']['App']['SchemaLoadBaseline'](arg1);
}

export function SchemaTables(arg1) {
  return window['go']['studioapp']['App']['SchemaTables'](arg1);
}

export function SecurityBootstrapAdmin(arg1, arg2) {
  return window['go']['studioapp']['App']['SecurityBootstrapAdmin'](arg1, arg2);
}

export function SecurityCreateRole(arg1) {
  return window['go']['studioapp']['App']['SecurityCreateRole'](arg1);
}

export function SecurityCreateUser(arg1, arg2) {
  return window['go']['studioapp']['App']['SecurityCreateUser'](arg1, arg2);
}

export function SecurityDeletePrincipal(arg1) {
  return window['go']['studioapp']['App']['SecurityDeletePrincipal'](arg1);
}

export function SecurityDisablePrincipal(arg1) {
  return window['go']['studioapp']['App']['SecurityDisablePrincipal'](arg1);
}

export function SecurityEnablePrincipal(arg1) {
  return window['go']['studioapp']['App']['SecurityEnablePrincipal'](arg1);
}

export function SecurityGrantHistoricalAccess(arg1) {
  return window['go']['studioapp']['App']['SecurityGrantHistoricalAccess'](arg1);
}

export function SecurityGrantPrivilege(arg1, arg2) {
  return window['go']['studioapp']['App']['SecurityGrantPrivilege'](arg1, arg2);
}

export function SecurityGrantRole(arg1, arg2) {
  return window['go']['studioapp']['App']['SecurityGrantRole'](arg1, arg2);
}

export function SecurityListPrincipals() {
  return window['go']['studioapp']['App']['SecurityListPrincipals']();
}

export function SecurityRecentAuditEvents(arg1) {
  return window['go']['studioapp']['App']['SecurityRecentAuditEvents'](arg1);
}

export function SecurityRevokePrivilege(arg1, arg2) {
  return window['go']['studioapp']['App']['SecurityRevokePrivilege'](arg1, arg2);
}

export function SecurityRevokeRole(arg1, arg2) {
  return window['go']['studioapp']['App']['SecurityRevokeRole'](arg1, arg2);
}

export function SecuritySetPassword(arg1, arg2) {
  return window['go']['studioapp']['App']['SecuritySetPassword'](arg1, arg2);
}

export function StartEntityChangeStream(arg1) {
  return window['go']['studioapp']['App']['StartEntityChangeStream'](arg1);
}

export function StopEntityChangeStream(arg1) {
  return window['go']['studioapp']['App']['StopEntityChangeStream'](arg1);
}

export function SwitchConnection(arg1) {
  return window['go']['studioapp']['App']['SwitchConnection'](arg1);
}

export function TemporalLookup(arg1) {
  return window['go']['studioapp']['App']['TemporalLookup'](arg1);
}

export function TimeTravel(arg1) {
  return window['go']['studioapp']['App']['TimeTravel'](arg1);
}

export function TimelineCommits(arg1) {
  return window['go']['studioapp']['App']['TimelineCommits'](arg1);
}
